<?php

return [
    "AFG" =>  [ "description" => "Afganistán", "zip_code_format" => null, "id_format" => null],
    "ALA" =>  [ "description" => "Islas Åland", "zip_code_format" => null, "id_format" => null],
    "ALB" =>  [ "description" => "Albania", "zip_code_format" => null, "id_format" => null],
    "DEU" =>  [ "description" => "Alemania", "zip_code_format" => null, "id_format" => null],
    "AND" =>  [ "description" => "Andorra", "zip_code_format" => null, "id_format" => null],
    "AGO" =>  [ "description" => "Angola", "zip_code_format" => null, "id_format" => null],
    "AIA" =>  [ "description" => "Anguila", "zip_code_format" => null, "id_format" => null],
    "ATA" =>  [ "description" => "Antártida", "zip_code_format" => null, "id_format" => null],
    "ATG" =>  [ "description" => "Antigua y Barbuda", "zip_code_format" => null, "id_format" => null],
    "SAU" =>  [ "description" => "Arabia Saudita", "zip_code_format" => null, "id_format" => null],
    "DZA" =>  [ "description" => "Argelia", "zip_code_format" => null, "id_format" => null],
    "ARG" =>  [ "description" => "Argentina", "zip_code_format" => null, "id_format" => null],
    "ARM" =>  [ "description" => "Armenia", "zip_code_format" => null, "id_format" => null],
    "ABW" =>  [ "description" => "Aruba", "zip_code_format" => null, "id_format" => null],
    "AUS" =>  [ "description" => "Australia", "zip_code_format" => null, "id_format" => null],
    "AUT" =>  [ "description" => "Austria", "zip_code_format" => null, "id_format" => null],
    "AZE" =>  [ "description" => "Azerbaiyán", "zip_code_format" => null, "id_format" => null],
    "BHS" =>  [ "description" => "Bahamas (las)", "zip_code_format" => null, "id_format" => null],
    "BGD" =>  [ "description" => "Bangladés", "zip_code_format" => null, "id_format" => null],
    "BRB" =>  [ "description" => "Barbados", "zip_code_format" => null, "id_format" => null],
    "BHR" =>  [ "description" => "Baréin", "zip_code_format" => null, "id_format" => null],
    "BEL" =>  [ "description" => "Bélgica", "zip_code_format" => null, "id_format" => null],
    "BLZ" =>  [ "description" => "Belice", "zip_code_format" => null, "id_format" => null],
    "BEN" =>  [ "description" => "Benín", "zip_code_format" => null, "id_format" => null],
    "BMU" =>  [ "description" => "Bermudas", "zip_code_format" => null, "id_format" => null],
    "BLR" =>  [ "description" => "Bielorrusia", "zip_code_format" => null, "id_format" => null],
    "MMR" =>  [ "description" => "Myanmar", "zip_code_format" => null, "id_format" => null],
    "BOL" =>  [ "description" => "Bolivia, Estado Plurinacional de", "zip_code_format" => null, "id_format" => null],
    "BIH" =>  [ "description" => "Bosnia y Herzegovina", "zip_code_format" => null, "id_format" => null],
    "BWA" =>  [ "description" => "Botsuana", "zip_code_format" => null, "id_format" => null],
    "BRA" =>  [ "description" => "Brasil", "zip_code_format" => null, "id_format" => null],
    "BRN" =>  [ "description" => "Brunéi Darussalam", "zip_code_format" => null, "id_format" => null],
    "BGR" =>  [ "description" => "Bulgaria", "zip_code_format" => null, "id_format" => null],
    "BFA" =>  [ "description" => "Burkina Faso", "zip_code_format" => null, "id_format" => null],
    "BDI" =>  [ "description" => "Burundi", "zip_code_format" => null, "id_format" => null],
    "BTN" =>  [ "description" => "Bután", "zip_code_format" => null, "id_format" => null],
    "CPV" =>  [ "description" => "Cabo Verde", "zip_code_format" => null, "id_format" => null],
    "KHM" =>  [ "description" => "Camboya", "zip_code_format" => null, "id_format" => null],
    "CMR" =>  [ "description" => "Camerún", "zip_code_format" => null, "id_format" => null],
    "CAN" =>  [ "description" => "Canadá", "zip_code_format" => "/^[A-Z][0-9][A-Z][0-9][A-Z][0-9]$/", "id_format" => "[0-9][9]"],
    "QAT" =>  [ "description" => "Catar", "zip_code_format" => null, "id_format" => null],
    "BES" =>  [ "description" => "Bonaire, San Eustaquio y Saba", "zip_code_format" => null, "id_format" => null],
    "TCD" =>  [ "description" => "Chad", "zip_code_format" => null, "id_format" => null],
    "CHL" =>  [ "description" => "Chile", "zip_code_format" => null, "id_format" => null],
    "CHN" =>  [ "description" => "China", "zip_code_format" => null, "id_format" => null],
    "CYP" =>  [ "description" => "Chipre", "zip_code_format" => null, "id_format" => null],
    "COL" =>  [ "description" => "Colombia", "zip_code_format" => null, "id_format" => null],
    "COM" =>  [ "description" => "Comoras", "zip_code_format" => null, "id_format" => null],
    "PRK" =>  [ "description" => "Corea (la República Democrática Popular de)", "zip_code_format" => null, "id_format" => null],
    "KOR" =>  [ "description" => "Corea (la República de)", "zip_code_format" => null, "id_format" => null],
    "CIV" =>  [ "description" => "Côte d'Ivoire", "zip_code_format" => null, "id_format" => null],
    "CRI" =>  [ "description" => "Costa Rica", "zip_code_format" => null, "id_format" => null],
    "HRV" =>  [ "description" => "Croacia", "zip_code_format" => null, "id_format" => null],
    "CUB" =>  [ "description" => "Cuba", "zip_code_format" => null, "id_format" => null],
    "CUW" =>  [ "description" => "Curaçao", "zip_code_format" => null, "id_format" => null],
    "DNK" =>  [ "description" => "Dinamarca", "zip_code_format" => null, "id_format" => null],
    "DMA" =>  [ "description" => "Dominica", "zip_code_format" => null, "id_format" => null],
    "ECU" =>  [ "description" => "Ecuador", "zip_code_format" => null, "id_format" => null],
    "EGY" =>  [ "description" => "Egipto", "zip_code_format" => null, "id_format" => null],
    "SLV" =>  [ "description" => "El Salvador", "zip_code_format" => null, "id_format" => null],
    "ARE" =>  [ "description" => "Emiratos Árabes Unidos (Los)", "zip_code_format" => null, "id_format" => null],
    "ERI" =>  [ "description" => "Eritrea", "zip_code_format" => null, "id_format" => null],
    "SVK" =>  [ "description" => "Eslovaquia", "zip_code_format" => null, "id_format" => null],
    "SVN" =>  [ "description" => "Eslovenia", "zip_code_format" => null, "id_format" => null],
    "ESP" =>  [ "description" => "España", "zip_code_format" => null, "id_format" => null],
    "USA" =>  [ "description" => "Estados Unidos (los)", "zip_code_format" => "/^[0-9][5](-[0-9][4])?$/", "id_format" => "[0-9][9]"],
    "EST" =>  [ "description" => "Estonia", "zip_code_format" => null, "id_format" => null],
    "ETH" =>  [ "description" => "Etiopía", "zip_code_format" => null, "id_format" => null],
    "PHL" =>  [ "description" => "Filipinas (las)", "zip_code_format" => null, "id_format" => null],
    "FIN" =>  [ "description" => "Finlandia", "zip_code_format" => null, "id_format" => null],
    "FJI" =>  [ "description" => "Fiyi", "zip_code_format" => null, "id_format" => null],
    "FRA" =>  [ "description" => "Francia", "zip_code_format" => null, "id_format" => null],
    "GAB" =>  [ "description" => "Gabón", "zip_code_format" => null, "id_format" => null],
    "GMB" =>  [ "description" => "Gambia (La)", "zip_code_format" => null, "id_format" => null],
    "GEO" =>  [ "description" => "Georgia", "zip_code_format" => null, "id_format" => null],
    "GHA" =>  [ "description" => "Ghana", "zip_code_format" => null, "id_format" => null],
    "GIB" =>  [ "description" => "Gibraltar", "zip_code_format" => null, "id_format" => null],
    "GRD" =>  [ "description" => "Granada", "zip_code_format" => null, "id_format" => null],
    "GRC" =>  [ "description" => "Grecia", "zip_code_format" => null, "id_format" => null],
    "GRL" =>  [ "description" => "Groenlandia", "zip_code_format" => null, "id_format" => null],
    "GLP" =>  [ "description" => "Guadalupe", "zip_code_format" => null, "id_format" => null],
    "GUM" =>  [ "description" => "Guam", "zip_code_format" => null, "id_format" => null],
    "GTM" =>  [ "description" => "Guatemala", "zip_code_format" => null, "id_format" => null],
    "GUF" =>  [ "description" => "Guayana Francesa", "zip_code_format" => null, "id_format" => null],
    "GGY" =>  [ "description" => "Guernsey", "zip_code_format" => null, "id_format" => null],
    "GIN" =>  [ "description" => "Guinea", "zip_code_format" => null, "id_format" => null],
    "GNB" =>  [ "description" => "Guinea-Bisáu", "zip_code_format" => null, "id_format" => null],
    "GNQ" =>  [ "description" => "Guinea Ecuatorial", "zip_code_format" => null, "id_format" => null],
    "GUY" =>  [ "description" => "Guyana", "zip_code_format" => null, "id_format" => null],
    "HTI" =>  [ "description" => "Haití", "zip_code_format" => null, "id_format" => null],
    "HND" =>  [ "description" => "Honduras", "zip_code_format" => null, "id_format" => null],
    "HKG" =>  [ "description" => "Hong Kong", "zip_code_format" => null, "id_format" => null],
    "HUN" =>  [ "description" => "Hungría", "zip_code_format" => null, "id_format" => null],
    "IND" =>  [ "description" => "India", "zip_code_format" => null, "id_format" => null],
    "IDN" =>  [ "description" => "Indonesia", "zip_code_format" => null, "id_format" => null],
    "IRQ" =>  [ "description" => "Irak", "zip_code_format" => null, "id_format" => null],
    "IRN" =>  [ "description" => "Irán (la República Islámica de)", "zip_code_format" => null, "id_format" => null],
    "IRL" =>  [ "description" => "Irlanda", "zip_code_format" => null, "id_format" => null],
    "BVT" =>  [ "description" => "Isla Bouvet", "zip_code_format" => null, "id_format" => null],
    "IMN" =>  [ "description" => "Isla de Man", "zip_code_format" => null, "id_format" => null],
    "CXR" =>  [ "description" => "Isla de Navidad", "zip_code_format" => null, "id_format" => null],
    "NFK" =>  [ "description" => "Isla Norfolk", "zip_code_format" => null, "id_format" => null],
    "ISL" =>  [ "description" => "Islandia", "zip_code_format" => null, "id_format" => null],
    "CYM" =>  [ "description" => "Islas Caimán (las)", "zip_code_format" => null, "id_format" => null],
    "CCK" =>  [ "description" => "Islas Cocos (Keeling)", "zip_code_format" => null, "id_format" => null],
    "COK" =>  [ "description" => "Islas Cook (las)", "zip_code_format" => null, "id_format" => null],
    "FRO" =>  [ "description" => "Islas Feroe (las)", "zip_code_format" => null, "id_format" => null],
    "SGS" =>  [ "description" => "Georgia del sur y las islas sandwich del sur", "zip_code_format" => null, "id_format" => null],
    "HMD" =>  [ "description" => "Isla Heard e Islas McDonald", "zip_code_format" => null, "id_format" => null],
    "FLK" =>  [ "description" => "Islas Malvinas [Falkland] (las)", "zip_code_format" => null, "id_format" => null],
    "MNP" =>  [ "description" => "Islas Marianas del Norte (las)", "zip_code_format" => null, "id_format" => null],
    "MHL" =>  [ "description" => "Islas Marshall (las)", "zip_code_format" => null, "id_format" => null],
    "PCN" =>  [ "description" => "Pitcairn", "zip_code_format" => null, "id_format" => null],
    "SLB" =>  [ "description" => "Islas Salomón (las)", "zip_code_format" => null, "id_format" => null],
    "TCA" =>  [ "description" => "Islas Turcas y Caicos (las)", "zip_code_format" => null, "id_format" => null],
    "UMI" =>  [ "description" => "Islas de Ultramar Menores de Estados Unidos (las)", "zip_code_format" => null, "id_format" => null],
    "VGB" =>  [ "description" => "Islas Vírgenes (Británicas)", "zip_code_format" => null, "id_format" => null],
    "VIR" =>  [ "description" => "Islas Vírgenes (EE.UU.)", "zip_code_format" => null, "id_format" => null],
    "ISR" =>  [ "description" => "Israel", "zip_code_format" => null, "id_format" => null],
    "ITA" =>  [ "description" => "Italia", "zip_code_format" => null, "id_format" => null],
    "JAM" =>  [ "description" => "Jamaica", "zip_code_format" => null, "id_format" => null],
    "JPN" =>  [ "description" => "Japón", "zip_code_format" => null, "id_format" => null],
    "JEY" =>  [ "description" => "Jersey", "zip_code_format" => null, "id_format" => null],
    "JOR" =>  [ "description" => "Jordania", "zip_code_format" => null, "id_format" => null],
    "KAZ" =>  [ "description" => "Kazajistán", "zip_code_format" => null, "id_format" => null],
    "KEN" =>  [ "description" => "Kenia", "zip_code_format" => null, "id_format" => null],
    "KGZ" =>  [ "description" => "Kirguistán", "zip_code_format" => null, "id_format" => null],
    "KIR" =>  [ "description" => "Kiribati", "zip_code_format" => null, "id_format" => null],
    "KWT" =>  [ "description" => "Kuwait", "zip_code_format" => null, "id_format" => null],
    "LAO" =>  [ "description" => "Lao, (la) República Democrática Popular", "zip_code_format" => null, "id_format" => null],
    "LSO" =>  [ "description" => "Lesoto", "zip_code_format" => null, "id_format" => null],
    "LVA" =>  [ "description" => "Letonia", "zip_code_format" => null, "id_format" => null],
    "LBN" =>  [ "description" => "Líbano", "zip_code_format" => null, "id_format" => null],
    "LBR" =>  [ "description" => "Liberia", "zip_code_format" => null, "id_format" => null],
    "LBY" =>  [ "description" => "Libia", "zip_code_format" => null, "id_format" => null],
    "LIE" =>  [ "description" => "Liechtenstein", "zip_code_format" => null, "id_format" => null],
    "LTU" =>  [ "description" => "Lituania", "zip_code_format" => null, "id_format" => null],
    "LUX" =>  [ "description" => "Luxemburgo", "zip_code_format" => null, "id_format" => null],
    "MAC" =>  [ "description" => "Macao", "zip_code_format" => null, "id_format" => null],
    "MDG" =>  [ "description" => "Madagascar", "zip_code_format" => null, "id_format" => null],
    "MYS" =>  [ "description" => "Malasia", "zip_code_format" => null, "id_format" => null],
    "MWI" =>  [ "description" => "Malaui", "zip_code_format" => null, "id_format" => null],
    "MDV" =>  [ "description" => "Maldivas", "zip_code_format" => null, "id_format" => null],
    "MLI" =>  [ "description" => "Malí", "zip_code_format" => null, "id_format" => null],
    "MLT" =>  [ "description" => "Malta", "zip_code_format" => null, "id_format" => null],
    "MAR" =>  [ "description" => "Marruecos", "zip_code_format" => null, "id_format" => null],
    "MTQ" =>  [ "description" => "Martinica", "zip_code_format" => null, "id_format" => null],
    "MUS" =>  [ "description" => "Mauricio", "zip_code_format" => null, "id_format" => null],
    "MRT" =>  [ "description" => "Mauritania", "zip_code_format" => null, "id_format" => null],
    "MYT" =>  [ "description" => "Mayotte", "zip_code_format" => null, "id_format" => null],
    "MEX" =>  [ "description" => "México", "zip_code_format" => "/^[0-9]{5}$/", "id_format" => "[A-Z&Ñ][3,4][0-9][2](0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9][2][0\n-9A]"],
    "FSM" =>  [ "description" => "Micronesia (los Estados Federados de)", "zip_code_format" => null, "id_format" => null],
    "MDA" =>  [ "description" => "Moldavia (la República de)", "zip_code_format" => null, "id_format" => null],
    "MCO" =>  [ "description" => "Mónaco", "zip_code_format" => null, "id_format" => null],
    "MNG" =>  [ "description" => "Mongolia", "zip_code_format" => null, "id_format" => null],
    "MNE" =>  [ "description" => "Montenegro", "zip_code_format" => null, "id_format" => null],
    "MSR" =>  [ "description" => "Montserrat", "zip_code_format" => null, "id_format" => null],
    "MOZ" =>  [ "description" => "Mozambique", "zip_code_format" => null, "id_format" => null],
    "NAM" =>  [ "description" => "Namibia", "zip_code_format" => null, "id_format" => null],
    "NRU" =>  [ "description" => "Nauru", "zip_code_format" => null, "id_format" => null],
    "NPL" =>  [ "description" => "Nepal", "zip_code_format" => null, "id_format" => null],
    "NIC" =>  [ "description" => "Nicaragua", "zip_code_format" => null, "id_format" => null],
    "NER" =>  [ "description" => "Níger (el)", "zip_code_format" => null, "id_format" => null],
    "NGA" =>  [ "description" => "Nigeria", "zip_code_format" => null, "id_format" => null],
    "NIU" =>  [ "description" => "Niue", "zip_code_format" => null, "id_format" => null],
    "NOR" =>  [ "description" => "Noruega", "zip_code_format" => null, "id_format" => null],
    "NCL" =>  [ "description" => "Nueva Caledonia", "zip_code_format" => null, "id_format" => null],
    "NZL" =>  [ "description" => "Nueva Zelanda", "zip_code_format" => null, "id_format" => null],
    "OMN" =>  [ "description" => "Omán", "zip_code_format" => null, "id_format" => null],
    "NLD" =>  [ "description" => "Países Bajos (los)", "zip_code_format" => null, "id_format" => null],
    "PAK" =>  [ "description" => "Pakistán", "zip_code_format" => null, "id_format" => null],
    "PLW" =>  [ "description" => "Palaos", "zip_code_format" => null, "id_format" => null],
    "PSE" =>  [ "description" => "Palestina, Estado de", "zip_code_format" => null, "id_format" => null],
    "PAN" =>  [ "description" => "Panamá", "zip_code_format" => null, "id_format" => null],
    "PNG" =>  [ "description" => "Papúa Nueva Guinea", "zip_code_format" => null, "id_format" => null],
    "PRY" =>  [ "description" => "Paraguay", "zip_code_format" => null, "id_format" => null],
    "PER" =>  [ "description" => "Perú", "zip_code_format" => null, "id_format" => null],
    "PYF" =>  [ "description" => "Polinesia Francesa", "zip_code_format" => null, "id_format" => null],
    "POL" =>  [ "description" => "Polonia", "zip_code_format" => null, "id_format" => null],
    "PRT" =>  [ "description" => "Portugal", "zip_code_format" => null, "id_format" => null],
    "PRI" =>  [ "description" => "Puerto Rico", "zip_code_format" => null, "id_format" => null],
    "GBR" =>  [ "description" => "Reino Unido (el)", "zip_code_format" => null, "id_format" => null],
    "CAF" =>  [ "description" => "República Centroafricana (la)", "zip_code_format" => null, "id_format" => null],
    "CZE" =>  [ "description" => "República Checa (la)", "zip_code_format" => null, "id_format" => null],
    "MKD" =>  [ "description" => "Macedonia (la antigua República Yugoslava de)", "zip_code_format" => null, "id_format" => null],
    "COG" =>  [ "description" => "Congo", "zip_code_format" => null, "id_format" => null],
    "COD" =>  [ "description" => "Congo (la República Democrática del)", "zip_code_format" => null, "id_format" => null],
    "DOM" =>  [ "description" => "República Dominicana (la)", "zip_code_format" => null, "id_format" => null],
    "REU" =>  [ "description" => "Reunión", "zip_code_format" => null, "id_format" => null],
    "RWA" =>  [ "description" => "Ruanda", "zip_code_format" => null, "id_format" => null],
    "ROU" =>  [ "description" => "Rumania", "zip_code_format" => null, "id_format" => null],
    "RUS" =>  [ "description" => "Rusia, (la) Federación de", "zip_code_format" => null, "id_format" => null],
    "ESH" =>  [ "description" => "Sahara Occidental", "zip_code_format" => null, "id_format" => null],
    "WSM" =>  [ "description" => "Samoa", "zip_code_format" => null, "id_format" => null],
    "ASM" =>  [ "description" => "Samoa Americana", "zip_code_format" => null, "id_format" => null],
    "BLM" =>  [ "description" => "San Bartolomé", "zip_code_format" => null, "id_format" => null],
    "KNA" =>  [ "description" => "San Cristóbal y Nieves", "zip_code_format" => null, "id_format" => null],
    "SMR" =>  [ "description" => "San Marino", "zip_code_format" => null, "id_format" => null],
    "MAF" =>  [ "description" => "San Martín (parte francesa)", "zip_code_format" => null, "id_format" => null],
    "SPM" =>  [ "description" => "San Pedro y Miquelón", "zip_code_format" => null, "id_format" => null],
    "VCT" =>  [ "description" => "San Vicente y las Granadinas", "zip_code_format" => null, "id_format" => null],
    "SHN" =>  [ "description" => "Santa Helena, Ascensión y Tristán de Acuña", "zip_code_format" => null, "id_format" => null],
    "LCA" =>  [ "description" => "Santa Lucía", "zip_code_format" => null, "id_format" => null],
    "STP" =>  [ "description" => "Santo Tomé y Príncipe", "zip_code_format" => null, "id_format" => null],
    "SEN" =>  [ "description" => "Senegal", "zip_code_format" => null, "id_format" => null],
    "SRB" =>  [ "description" => "Serbia", "zip_code_format" => null, "id_format" => null],
    "SYC" =>  [ "description" => "Seychelles", "zip_code_format" => null, "id_format" => null],
    "SLE" =>  [ "description" => "Sierra leona", "zip_code_format" => null, "id_format" => null],
    "SGP" =>  [ "description" => "Singapur", "zip_code_format" => null, "id_format" => null],
    "SXM" =>  [ "description" => "Sint Maarten (parte holandesa)", "zip_code_format" => null, "id_format" => null],
    "SYR" =>  [ "description" => "Siria, (la) República Árabe", "zip_code_format" => null, "id_format" => null],
    "SOM" =>  [ "description" => "Somalia", "zip_code_format" => null, "id_format" => null],
    "LKA" =>  [ "description" => "Sri Lanka", "zip_code_format" => null, "id_format" => null],
    "SWZ" =>  [ "description" => "Suazilandia", "zip_code_format" => null, "id_format" => null],
    "ZAF" =>  [ "description" => "Sudáfrica", "zip_code_format" => null, "id_format" => null],
    "SDN" =>  [ "description" => "Sudán (el)", "zip_code_format" => null, "id_format" => null],
    "SSD" =>  [ "description" => "Sudán del Sur", "zip_code_format" => null, "id_format" => null],
    "SWE" =>  [ "description" => "Suecia", "zip_code_format" => null, "id_format" => null],
    "CHE" =>  [ "description" => "Suiza", "zip_code_format" => null, "id_format" => null],
    "SUR" =>  [ "description" => "Surinam", "zip_code_format" => null, "id_format" => null],
    "SJM" =>  [ "description" => "Svalbard y Jan Mayen", "zip_code_format" => null, "id_format" => null],
    "THA" =>  [ "description" => "Tailandia", "zip_code_format" => null, "id_format" => null],
    "TWN" =>  [ "description" => "Taiwán (Provincia de China)", "zip_code_format" => null, "id_format" => null],
    "TZA" =>  [ "description" => "Tanzania, República Unida de", "zip_code_format" => null, "id_format" => null],
    "TJK" =>  [ "description" => "Tayikistán", "zip_code_format" => null, "id_format" => null],
    "IOT" =>  [ "description" => "Territorio Británico del Océano Índico (el)", "zip_code_format" => null, "id_format" => null],
    "ATF" =>  [ "description" => "Territorios Australes Franceses (los)", "zip_code_format" => null, "id_format" => null],
    "TLS" =>  [ "description" => "Timor-Leste", "zip_code_format" => null, "id_format" => null],
    "TGO" =>  [ "description" => "Togo", "zip_code_format" => null, "id_format" => null],
    "TKL" =>  [ "description" => "Tokelau", "zip_code_format" => null, "id_format" => null],
    "TON" =>  [ "description" => "Tonga", "zip_code_format" => null, "id_format" => null],
    "TTO" =>  [ "description" => "Trinidad y Tobago", "zip_code_format" => null, "id_format" => null],
    "TUN" =>  [ "description" => "Túnez", "zip_code_format" => null, "id_format" => null],
    "TKM" =>  [ "description" => "Turkmenistán", "zip_code_format" => null, "id_format" => null],
    "TUR" =>  [ "description" => "Turquía", "zip_code_format" => null, "id_format" => null],
    "TUV" =>  [ "description" => "Tuvalu", "zip_code_format" => null, "id_format" => null],
    "UKR" =>  [ "description" => "Ucrania", "zip_code_format" => null, "id_format" => null],
    "UGA" =>  [ "description" => "Uganda", "zip_code_format" => null, "id_format" => null],
    "URY" =>  [ "description" => "Uruguay", "zip_code_format" => null, "id_format" => null],
    "UZB" =>  [ "description" => "Uzbekistán", "zip_code_format" => null, "id_format" => null],
    "VUT" =>  [ "description" => "Vanuatu", "zip_code_format" => null, "id_format" => null],
    "VAT" =>  [ "description" => "Santa Sede[Estado de la Ciudad del Vaticano] (la)", "zip_code_format" => null, "id_format" => null],
    "VEN" =>  [ "description" => "Venezuela, República Bolivariana de", "zip_code_format" => null, "id_format" => null],
    "VNM" =>  [ "description" => "Viet Nam", "zip_code_format" => null, "id_format" => null],
    "WLF" =>  [ "description" => "Wallis y Futuna", "zip_code_format" => null, "id_format" => null],
    "YEM" =>  [ "description" => "Yemen", "zip_code_format" => null, "id_format" => null],
    "DJI" =>  [ "description" => "Yibuti", "zip_code_format" => null, "id_format" => null],
    "ZMB" =>  [ "description" => "Zambia", "zip_code_format" => null, "id_format" => null],
    "ZWE" =>  [ "description" => "Zimbabue", "zip_code_format" => null, "id_format" => null],
    "ZZZ" =>  [ "description" => "Países no declarados", "zip_code_format" => null, "id_format" => null]
];