<?php

return [
	"states" => [
		"AGU" =>	"Aguascalientes",
		"BCN" =>	"Baja California",
		"BCS" =>	"Baja California Sur",
		"CAM" =>	"Campeche",
		"CHP" =>	"Chiapas",
		"CHH" =>	"Chihuahua",
		"COA" =>	"Coahuila",
		"COL" =>	"Colima",
		"DIF" =>	"Ciudad de México",
		"DUR" =>	"Durango",
		"GUA" =>	"Guanajuato",
		"GRO" =>	"Guerrero",
		"HID" =>	"Hidalgo",
		"JAL" =>	"Jalisco",
		"MEX" =>	"México",
		"MIC" =>	"Michoacán",
		"MOR" =>	"Morelos",
		"NAY" =>	"Nayarit",
		"NLE" =>	"Nuevo León",
		"OAX" =>	"Oaxaca",
		"PUE" =>	"Puebla",
		"QTO" =>	"Querétaro",
		"ROO" =>	"Quintana Roo",
		"SLP" =>	"San Luis Potosí",
		"SIN" =>	"Sinaloa",
		"SON" =>	"Sonora",
		"TAB" =>	"Tabasco",
		"TAM" =>	"Tamaulipas",
		"TLA" =>	"Tlaxcala",
		"VER" =>	"Veracruz",
		"YUC" =>	"Yucatán",
		"ZAC" =>	"Zacatecas",
	],
	"process_type" => [
		"Ordinario" 	=> "Ordinario",
		"Precampaña" 	=> "Precampaña",
		"Campaña" 		=> "Campaña",
	],
	'committee_type' => [
		"Ejecutivo Nacional" 	=> "Ejecutivo Nacional",
		"Ejecutivo Estatal" 	=> "Ejecutivo Estatal",
		"Directivo Estatal" 	=> "Directivo Estatal",
	],
];
