<?php

return [
    '_01' => 'Efectivo',
    '_02' => 'Cheque nominativo',
    '_03' => 'Transferencia electrónica de fondos',
    '_04' => 'Tarjeta de crédito',
    '_05' => 'Monedero electrónico',
    '_06' => 'Dinero electrónico',
    '_08' => 'Vales de despensa',
    '_12' => 'Dación en pago',
    '_13' => 'Pago por subrogación',
    '_14' => 'Pago por consignación',
    '_15' => 'Condonación',
    '_17' => 'Compensación',
    '_23' => 'Novación',
    '_24' => 'Confusión',
    '_25' => 'Remisión de deuda',
    '_26' => 'Prescripción o caducidad',
    '_27' => 'A satisfacción del acreedor',
    '_28' => 'Tarjeta de débito',
    '_29' => 'Tarjeta de servicios',
    '_30' => 'Aplicación de anticipos',
    '_31' => 'Intermediario pagos',
    '_99' => 'Por definir',
];
